name: responsive_dashboard
description: A responsive Flutter dashboard for all devices
publish_to: "none"

version: 1.0.0+1 

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.65.0
  intl: ^0.18.1

flutter:
  uses-material-design: true
